### ISSUE TITLE
[Latte dock] Auto-hide stops working when menu is opened

### ISSUE THREAD

**Issue by aliquo93** [prateekmedia/Menu11#33] opened 2021-08-28 22:22 UTC
If I click the app menu directly from Latte Dock with the mouse, there are no problems, but if I press the "Super" button on the keyboard, Latte Dock stops to auto-hide on maximized applications and I'm forced to close and reopen Latte Dock to make it work again.

Bug already reported (and confirmed) on: [https://bugs.kde.org/show_bug.cgi?id=441053](url)

I've also attached a video that shows the issue.

https://user-images.githubusercontent.com/9071297/131232417-c72e119c-fe95-45b2-add9-77783ada9590.mp4

**Comment by prateekmedia** [comment] 2021-08-29 03:58
Can you check if it persists if you set position from `configure menu11` to Auto.

**Comment by aliquo93** [comment] 2021-08-29 16:18
> Can you check if it persists if you set position from `configure menu11` to Auto.

Yes, happen also with "Auto".

**Comment by FForkist** [comment] 2021-09-12 23:07
Same thing goes in my latte dock setup. A temporary workaround i've found was to right click the dock and click outside instead of completely restarting latte-dock.

**Comment by KBeDevel** [comment] 2021-09-16 14:43
Same here. It also happens (using any Menu11 position configuration)

I can dismiss the dock by right-clicking any place in the dock, even when the "start menu" is still visible, after this action, any left-click outside the menu and/or dock will dismiss the menu and will trigger the latte auto-hide effect as expected.

Additional context:
- OS: Fedora 34 Workstation KDE Spin
- KDE Plasma version: 5.22.5
- KDE Framework version: 5.86.0
- Qt version: 5.15.2
- KWin source: [low-latency COPR](https://copr.fedorainfracloud.org/coprs/zawertun/kde/)
- Wayland?: no
- Latte Dock version: 0.10.1
- Latte Dock launcher group: Global
- Using multiple activities?: yes (3)
- Using multiple virtual desktops?: yes (4)

**Comment by prateekmedia** [comment] 2021-09-16 14:46
The problem is that I don't use latte dock or know much about it, If anbody has a solution then I would be happy to merge it.

**Comment by Anti-Shulk** [comment] 2021-09-27 18:14
I am also experiencing this bug. Since Menu 11 is forked from Menu Z, I tested this issue on menu Z, but it does not occur. I noticed this bug happens with applications launchers that do not have an indicator when clicked on in Latte dock (it also happens in onzemenu), but it does not happen in application launchers such as Menu Z and Plasma's default Application Launcher which do have an indicator underneath them in Latte dock for me at least. Sorry I could not bring any more info on this issue.

**Comment by prateekmedia** [comment] 2021-09-28 02:51
@Anti-Shulk This is most likely happening due to below line:
https://github.com/prateekmedia/Menu11/blob/99042ec24f2567321a6b53c29e0444e7c96d48cc/contents/ui/MenuRepresentation.qml#L74-L123

It is happenin mostly cause this applet is try to position itself in custom coordinates (which is in fact taken from ditto menu (which onze menu also has)) that's why this problem is common in onze menu and menu 11.

The only right way to do it is to rewrite this MenuRepresentation file to better positioning system.

**Comment by prateekmedia** [comment] 2021-11-17 09:05
Latte dock v0.10.3 is released 20 days ago and it has the patch that would fix this, So I will close the issue for now.

**Closed by prateekmedia** 2021-11-17 09:05 UTC
Labels: bug, hacktoberfest

**Comment by aliquo93** [comment] 2021-11-17 16:35
@psifidotos @prateekmedia  Congtratulations to both of you for the great work!
